@api = http://localhost:4000/tasks

### get all tasks
GET {{api}}

### create task
POST {{api}}
Content-Type: application/json

{
  "title": "some title",
  "description": "some description"
}

### get task
GET {{api}}/2

### delete a task
DELETE {{api}}/1

### update task
PUT {{api}}/3
Content-Type: application/json

{
  "title": "some new title",
  "description": "some new description"
}

### count
GET {{api}}/count