@api = http://localhost:4000/api/tasks

### get all tasks
GET {{api}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY0OTA0MTM3OSwiZXhwIjoxNjQ5MTI3Nzc5fQ.yZl_JWWFie8461YWh6ULy1hvT4uICrVHj0zC4dDD28A

### create task
POST {{api}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY0OTA0MTM3OSwiZXhwIjoxNjQ5MTI3Nzc5fQ.yZl_JWWFie8461YWh6ULy1hvT4uICrVHj0zC4dDD28A

{
  "title": "joe task",
  "description": "some description joe"
}

### get task
GET {{api}}/2

### delete a task
DELETE {{api}}/1

### update task
PUT {{api}}/3
Content-Type: application/json

{
  "title": "some new title",
  "description": "some new description"
}

### count
GET {{api}}/count