version: "3.8"

services:
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: faztpassword
      POSTGRES_DB: tasksdb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  ui:
    container_name: pgadmin
    image: dpage/pgadmin4
    logging: 
      driver: none
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
